name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: echo '${{secrets.GITHUB_TOKEN}}' | podman login ghcr.io -u '${{github.actor}}' --password-stdin
      - name: Build
        run: podman build --platform=linux/386 -t localhost/rocky-i686-container:latest .
      - name: Push
        if: github.event_name != 'pull_request'
        run: podman push localhost/rocky-i686-container:latest ghcr.io/charles25565/rocky-i686-container:9
